---
site_name: NetBox ACI Plugin
site_url: https://pheus.github.io/netbox-aci-plugin
repo_url: https://github.com/pheus/netbox-aci-plugin
repo_name: pheus/netbox-aci-plugin
# strict: true
nav:
  - Home: index.md
  - Features:
      - Tenants: features/tenants.md
  - Development:
      - Contributing: development/contributing.md
      - Releasing: development/releasing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  # logo: assets/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs.sticky
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 1
      permalink: '#'
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pheus/netbox-aci-plugin
      name: Github
watch:
  - netbox_aci_plugin
...
