# See PEP 518 for the spec of this file
# https://www.python.org/dev/peps/pep-0518/

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name =  "netbox-aci-plugin"
version = "0.0.13"
requires-python = ">=3.10.0"
authors = [
    {name = "Martin Hauser", email = "git@pheus.dev"},
]
maintainers = [
    {name = "Martin Hauser", email = "git@pheus.dev"},
]
description = "NetBox plugin for Cisco ACI."
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    "Framework :: Django",
    'Intended Audience :: Developers',
    "Intended Audience :: System Administrators",
    'Natural Language :: English',
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
]

[project.optional-dependencies]
docs = [
    "mkdocs==1.6.1",
    "mkdocs-material==9.6.18",
    "mkdocs-include-markdown-plugin==7.1.7",
]
test = [
    "check-manifest==0.50",
    "isort==6.0.1",
    "pre-commit==4.3.0",
    "pytest==8.4.1",
    "ruff==0.12.11",
    "yamllint==1.37.1",
]

[project.urls]
Documentation = "https://github.com/pheus/netbox-aci-plugin/blob/main/README.md"
Repository = "https://github.com/pheus/netbox-aci-plugin"
Issues = "https://github.com/pheus/netbox-aci-plugin/issues"

[tool.isort]
line_length = 79
profile = "black"

[tool.ruff]
line-length = 79
# Always generate Python 3.10-compatible code.
target_version = "py310"

[tool.setuptools.package-data]
netbox_aci_plugin = ["templates/**"]
