from .access_policies.aaep import (
    ACIAAEPDomainBindingBulkDeleteView,
    ACIAAEPDomainBindingBulkEditView,
    ACIAAEPDomainBindingBulkImportView,
    ACIAAEPDomainBindingEditView,
    ACIAAEPDomainBindingListView,
    ACIAAEPDomainBindingView,
    ACIAttachableAccessEntityProfileBulkDeleteView,
    ACIAttachableAccessEntityProfileBulkEditView,
    ACIAttachableAccessEntityProfileBulkImportView,
    ACIAttachableAccessEntityProfileEditView,
    ACIAttachableAccessEntityProfileListView,
    ACIAttachableAccessEntityProfileView,
)
from .access_policies.domains import (
    ACIPhysicalDomainBulkDeleteView,
    ACIPhysicalDomainBulkEditView,
    ACIPhysicalDomainBulkImportView,
    ACIPhysicalDomainEditView,
    ACIPhysicalDomainListView,
    ACIPhysicalDomainView,
    ACIRoutedDomainBulkDeleteView,
    ACIRoutedDomainBulkEditView,
    ACIRoutedDomainBulkImportView,
    ACIRoutedDomainEditView,
    ACIRoutedDomainListView,
    ACIRoutedDomainView,
)
from .access_policies.interface_policy_groups import (
    ACILeafInterfacePolicyGroupBulkDeleteView,
    ACILeafInterfacePolicyGroupBulkEditView,
    ACILeafInterfacePolicyGroupBulkImportView,
    ACILeafInterfacePolicyGroupEditView,
    ACILeafInterfacePolicyGroupListView,
    ACILeafInterfacePolicyGroupView,
)
from .access_policies.leaf_interface_overrides import (
    ACILeafInterfaceOverrideBulkDeleteView,
    ACILeafInterfaceOverrideBulkEditView,
    ACILeafInterfaceOverrideBulkImportView,
    ACILeafInterfaceOverrideEditView,
    ACILeafInterfaceOverrideListView,
    ACILeafInterfaceOverrideView,
)
from .access_policies.leaf_interface_profiles import (
    ACILeafInterfaceProfileBulkDeleteView,
    ACILeafInterfaceProfileBulkEditView,
    ACILeafInterfaceProfileBulkImportView,
    ACILeafInterfaceProfileEditView,
    ACILeafInterfaceProfileListView,
    ACILeafInterfaceProfileView,
    ACILeafInterfaceSelectorBulkDeleteView,
    ACILeafInterfaceSelectorBulkEditView,
    ACILeafInterfaceSelectorBulkImportView,
    ACILeafInterfaceSelectorEditView,
    ACILeafInterfaceSelectorListView,
    ACILeafInterfaceSelectorView,
    ACILeafPortBlockBulkDeleteView,
    ACILeafPortBlockBulkEditView,
    ACILeafPortBlockBulkImportView,
    ACILeafPortBlockEditView,
    ACILeafPortBlockListView,
    ACILeafPortBlockView,
)
from .access_policies.leaf_switch_profiles import (
    ACILeafNodeBlockBulkDeleteView,
    ACILeafNodeBlockBulkEditView,
    ACILeafNodeBlockBulkImportView,
    ACILeafNodeBlockEditView,
    ACILeafNodeBlockListView,
    ACILeafNodeBlockView,
    ACILeafSelectorBulkDeleteView,
    ACILeafSelectorBulkEditView,
    ACILeafSelectorBulkImportView,
    ACILeafSelectorEditView,
    ACILeafSelectorListView,
    ACILeafSelectorView,
    ACILeafSwitchProfileBulkDeleteView,
    ACILeafSwitchProfileBulkEditView,
    ACILeafSwitchProfileBulkImportView,
    ACILeafSwitchProfileEditView,
    ACILeafSwitchProfileInterfaceBindingBulkDeleteView,
    ACILeafSwitchProfileInterfaceBindingBulkEditView,
    ACILeafSwitchProfileInterfaceBindingBulkImportView,
    ACILeafSwitchProfileInterfaceBindingEditView,
    ACILeafSwitchProfileInterfaceBindingListView,
    ACILeafSwitchProfileInterfaceBindingView,
    ACILeafSwitchProfileListView,
    ACILeafSwitchProfileView,
)
from .access_policies.vlan_pools import (
    ACIVLANPoolBulkDeleteView,
    ACIVLANPoolBulkEditView,
    ACIVLANPoolBulkImportView,
    ACIVLANPoolEditView,
    ACIVLANPoolListView,
    ACIVLANPoolRangeBulkDeleteView,
    ACIVLANPoolRangeBulkEditView,
    ACIVLANPoolRangeBulkImportView,
    ACIVLANPoolRangeEditView,
    ACIVLANPoolRangeListView,
    ACIVLANPoolRangeView,
    ACIVLANPoolView,
)
from .fabric.fabrics import (
    ACIFabricBulkDeleteView,
    ACIFabricBulkEditView,
    ACIFabricBulkImportView,
    ACIFabricEditView,
    ACIFabricListView,
    ACIFabricView,
)
from .fabric.node_interfaces import (
    ACINodeInterfaceBulkDeleteView,
    ACINodeInterfaceBulkEditView,
    ACINodeInterfaceBulkImportView,
    ACINodeInterfaceEditView,
    ACINodeInterfaceListView,
    ACINodeInterfaceView,
)
from .fabric.nodes import (
    ACINodeBulkDeleteView,
    ACINodeBulkEditView,
    ACINodeBulkImportView,
    ACINodeEditView,
    ACINodeListView,
    ACINodeView,
)
from .fabric.pods import (
    ACIPodBulkDeleteView,
    ACIPodBulkEditView,
    ACIPodBulkImportView,
    ACIPodEditView,
    ACIPodListView,
    ACIPodView,
)
from .fabric.vpc_protection_groups import (
    ACIVPCProtectionGroupBulkDeleteView,
    ACIVPCProtectionGroupBulkEditView,
    ACIVPCProtectionGroupBulkImportView,
    ACIVPCProtectionGroupEditView,
    ACIVPCProtectionGroupListView,
    ACIVPCProtectionGroupView,
)
from .tenant.app_profiles import (
    ACIAppProfileBulkDeleteView,
    ACIAppProfileBulkEditView,
    ACIAppProfileBulkImportView,
    ACIAppProfileEditView,
    ACIAppProfileListView,
    ACIAppProfileView,
)
from .tenant.bridge_domains import (
    ACIBridgeDomainBulkDeleteView,
    ACIBridgeDomainBulkEditView,
    ACIBridgeDomainBulkImportView,
    ACIBridgeDomainEditView,
    ACIBridgeDomainL3OutBindingBulkDeleteView,
    ACIBridgeDomainL3OutBindingBulkEditView,
    ACIBridgeDomainL3OutBindingBulkImportView,
    ACIBridgeDomainL3OutBindingEditView,
    ACIBridgeDomainL3OutBindingListView,
    ACIBridgeDomainL3OutBindingView,
    ACIBridgeDomainListView,
    ACIBridgeDomainSubnetBulkDeleteView,
    ACIBridgeDomainSubnetBulkEditView,
    ACIBridgeDomainSubnetBulkImportView,
    ACIBridgeDomainSubnetEditView,
    ACIBridgeDomainSubnetListView,
    ACIBridgeDomainSubnetView,
    ACIBridgeDomainView,
)
from .tenant.contract_filters import (
    ACIContractFilterBulkDeleteView,
    ACIContractFilterBulkEditView,
    ACIContractFilterBulkImportView,
    ACIContractFilterEditView,
    ACIContractFilterEntryBulkDeleteView,
    ACIContractFilterEntryBulkEditView,
    ACIContractFilterEntryBulkImportView,
    ACIContractFilterEntryEditView,
    ACIContractFilterEntryListView,
    ACIContractFilterEntryView,
    ACIContractFilterListView,
    ACIContractFilterView,
)
from .tenant.contracts import (
    ACIContractBulkDeleteView,
    ACIContractBulkEditView,
    ACIContractBulkImportView,
    ACIContractEditView,
    ACIContractListView,
    ACIContractRelationBulkDeleteView,
    ACIContractRelationBulkEditView,
    ACIContractRelationBulkImportView,
    ACIContractRelationEditView,
    ACIContractRelationListView,
    ACIContractRelationView,
    ACIContractSubjectBulkDeleteView,
    ACIContractSubjectBulkEditView,
    ACIContractSubjectBulkImportView,
    ACIContractSubjectEditView,
    ACIContractSubjectFilterBulkDeleteView,
    ACIContractSubjectFilterBulkEditView,
    ACIContractSubjectFilterBulkImportView,
    ACIContractSubjectFilterEditView,
    ACIContractSubjectFilterListView,
    ACIContractSubjectFilterView,
    ACIContractSubjectListView,
    ACIContractSubjectView,
    ACIContractView,
)
from .tenant.endpoint_group_bindings import (
    ACIEndpointGroupAAEPBindingBulkDeleteView,
    ACIEndpointGroupAAEPBindingBulkEditView,
    ACIEndpointGroupAAEPBindingBulkImportView,
    ACIEndpointGroupAAEPBindingEditView,
    ACIEndpointGroupAAEPBindingListView,
    ACIEndpointGroupAAEPBindingView,
    ACIEndpointGroupDomainBindingBulkDeleteView,
    ACIEndpointGroupDomainBindingBulkEditView,
    ACIEndpointGroupDomainBindingBulkImportView,
    ACIEndpointGroupDomainBindingEditView,
    ACIEndpointGroupDomainBindingListView,
    ACIEndpointGroupDomainBindingView,
)
from .tenant.endpoint_groups import (
    ACIEndpointGroupBulkDeleteView,
    ACIEndpointGroupBulkEditView,
    ACIEndpointGroupBulkImportView,
    ACIEndpointGroupEditView,
    ACIEndpointGroupListView,
    ACIEndpointGroupView,
    ACIUSegEndpointGroupBulkDeleteView,
    ACIUSegEndpointGroupBulkEditView,
    ACIUSegEndpointGroupBulkImportView,
    ACIUSegEndpointGroupEditView,
    ACIUSegEndpointGroupListView,
    ACIUSegEndpointGroupView,
    ACIUSegNetworkAttributeBulkDeleteView,
    ACIUSegNetworkAttributeBulkEditView,
    ACIUSegNetworkAttributeBulkImportView,
    ACIUSegNetworkAttributeEditView,
    ACIUSegNetworkAttributeListView,
    ACIUSegNetworkAttributeView,
)
from .tenant.endpoint_security_groups import (
    ACIEndpointSecurityGroupBulkDeleteView,
    ACIEndpointSecurityGroupBulkEditView,
    ACIEndpointSecurityGroupBulkImportView,
    ACIEndpointSecurityGroupEditView,
    ACIEndpointSecurityGroupListView,
    ACIEndpointSecurityGroupView,
    ACIEsgEndpointGroupSelectorBulkDeleteView,
    ACIEsgEndpointGroupSelectorBulkEditView,
    ACIEsgEndpointGroupSelectorBulkImportView,
    ACIEsgEndpointGroupSelectorEditView,
    ACIEsgEndpointGroupSelectorListView,
    ACIEsgEndpointGroupSelectorView,
    ACIEsgEndpointSelectorBulkDeleteView,
    ACIEsgEndpointSelectorBulkEditView,
    ACIEsgEndpointSelectorBulkImportView,
    ACIEsgEndpointSelectorEditView,
    ACIEsgEndpointSelectorListView,
    ACIEsgEndpointSelectorView,
)
from .tenant.l3outs import (
    ACIExternalEndpointGroupBulkDeleteView,
    ACIExternalEndpointGroupBulkEditView,
    ACIExternalEndpointGroupBulkImportView,
    ACIExternalEndpointGroupEditView,
    ACIExternalEndpointGroupListView,
    ACIExternalEndpointGroupView,
    ACIExternalSubnetBulkDeleteView,
    ACIExternalSubnetBulkEditView,
    ACIExternalSubnetBulkImportView,
    ACIExternalSubnetEditView,
    ACIExternalSubnetListView,
    ACIExternalSubnetView,
    ACIL3OutBulkDeleteView,
    ACIL3OutBulkEditView,
    ACIL3OutBulkImportView,
    ACIL3OutEditView,
    ACIL3OutListView,
    ACIL3OutView,
)
from .tenant.tenants import (
    ACITenantBulkDeleteView,
    ACITenantBulkEditView,
    ACITenantBulkImportView,
    ACITenantEditView,
    ACITenantListView,
    ACITenantView,
)
from .tenant.vrfs import (
    ACIVRFBulkDeleteView,
    ACIVRFBulkEditView,
    ACIVRFBulkImportView,
    ACIVRFEditView,
    ACIVRFListView,
    ACIVRFView,
)

__all__ = (
    # ACIAAEPDomainBinding
    "ACIAAEPDomainBindingBulkDeleteView",
    "ACIAAEPDomainBindingBulkEditView",
    "ACIAAEPDomainBindingBulkImportView",
    "ACIAAEPDomainBindingEditView",
    "ACIAAEPDomainBindingListView",
    "ACIAAEPDomainBindingView",
    # ACIAppProfile
    "ACIAppProfileBulkDeleteView",
    "ACIAppProfileBulkEditView",
    "ACIAppProfileBulkImportView",
    "ACIAppProfileEditView",
    "ACIAppProfileListView",
    "ACIAppProfileView",
    # ACIAttachableAccessEntityProfile
    "ACIAttachableAccessEntityProfileBulkDeleteView",
    "ACIAttachableAccessEntityProfileBulkEditView",
    "ACIAttachableAccessEntityProfileBulkImportView",
    "ACIAttachableAccessEntityProfileEditView",
    "ACIAttachableAccessEntityProfileListView",
    "ACIAttachableAccessEntityProfileView",
    # ACIBridgeDomain
    "ACIBridgeDomainBulkDeleteView",
    "ACIBridgeDomainBulkEditView",
    "ACIBridgeDomainBulkImportView",
    "ACIBridgeDomainEditView",
    "ACIBridgeDomainListView",
    "ACIBridgeDomainView",
    # ACIBridgeDomainL3OutBinding
    "ACIBridgeDomainL3OutBindingBulkDeleteView",
    "ACIBridgeDomainL3OutBindingBulkEditView",
    "ACIBridgeDomainL3OutBindingBulkImportView",
    "ACIBridgeDomainL3OutBindingEditView",
    "ACIBridgeDomainL3OutBindingListView",
    "ACIBridgeDomainL3OutBindingView",
    # ACIBridgeDomainSubnet
    "ACIBridgeDomainSubnetBulkDeleteView",
    "ACIBridgeDomainSubnetBulkEditView",
    "ACIBridgeDomainSubnetBulkImportView",
    "ACIBridgeDomainSubnetEditView",
    "ACIBridgeDomainSubnetListView",
    "ACIBridgeDomainSubnetView",
    # ACIContract
    "ACIContractBulkDeleteView",
    "ACIContractBulkEditView",
    "ACIContractBulkImportView",
    "ACIContractEditView",
    "ACIContractListView",
    "ACIContractView",
    # ACIContractFilter
    "ACIContractFilterBulkDeleteView",
    "ACIContractFilterBulkEditView",
    "ACIContractFilterBulkImportView",
    "ACIContractFilterEditView",
    "ACIContractFilterListView",
    "ACIContractFilterView",
    # ACIContractFilterEntry
    "ACIContractFilterEntryBulkDeleteView",
    "ACIContractFilterEntryBulkEditView",
    "ACIContractFilterEntryBulkImportView",
    "ACIContractFilterEntryEditView",
    "ACIContractFilterEntryListView",
    "ACIContractFilterEntryView",
    # ACIContractRelation
    "ACIContractRelationBulkDeleteView",
    "ACIContractRelationBulkEditView",
    "ACIContractRelationBulkImportView",
    "ACIContractRelationEditView",
    "ACIContractRelationListView",
    "ACIContractRelationView",
    # ACIContractSubject
    "ACIContractSubjectBulkDeleteView",
    "ACIContractSubjectBulkEditView",
    "ACIContractSubjectBulkImportView",
    "ACIContractSubjectEditView",
    "ACIContractSubjectListView",
    "ACIContractSubjectView",
    # ACIContractSubjectFilter
    "ACIContractSubjectFilterBulkDeleteView",
    "ACIContractSubjectFilterBulkEditView",
    "ACIContractSubjectFilterBulkImportView",
    "ACIContractSubjectFilterEditView",
    "ACIContractSubjectFilterListView",
    "ACIContractSubjectFilterView",
    # ACIEndpointGroup
    "ACIEndpointGroupBulkDeleteView",
    "ACIEndpointGroupBulkEditView",
    "ACIEndpointGroupBulkImportView",
    "ACIEndpointGroupEditView",
    "ACIEndpointGroupListView",
    "ACIEndpointGroupView",
    # ACIEndpointGroupAAEPBinding
    "ACIEndpointGroupAAEPBindingBulkDeleteView",
    "ACIEndpointGroupAAEPBindingBulkEditView",
    "ACIEndpointGroupAAEPBindingBulkImportView",
    "ACIEndpointGroupAAEPBindingEditView",
    "ACIEndpointGroupAAEPBindingListView",
    "ACIEndpointGroupAAEPBindingView",
    # ACIEndpointGroupDomainBinding
    "ACIEndpointGroupDomainBindingBulkDeleteView",
    "ACIEndpointGroupDomainBindingBulkEditView",
    "ACIEndpointGroupDomainBindingBulkImportView",
    "ACIEndpointGroupDomainBindingEditView",
    "ACIEndpointGroupDomainBindingListView",
    "ACIEndpointGroupDomainBindingView",
    # ACIEndpointSecurityGroup
    "ACIEndpointSecurityGroupBulkDeleteView",
    "ACIEndpointSecurityGroupBulkEditView",
    "ACIEndpointSecurityGroupBulkImportView",
    "ACIEndpointSecurityGroupEditView",
    "ACIEndpointSecurityGroupListView",
    "ACIEndpointSecurityGroupView",
    # ACIEsgEndpointGroupSelector
    "ACIEsgEndpointGroupSelectorBulkDeleteView",
    "ACIEsgEndpointGroupSelectorBulkEditView",
    "ACIEsgEndpointGroupSelectorBulkImportView",
    "ACIEsgEndpointGroupSelectorEditView",
    "ACIEsgEndpointGroupSelectorListView",
    "ACIEsgEndpointGroupSelectorView",
    # ACIEsgEndpointSelector
    "ACIEsgEndpointSelectorBulkDeleteView",
    "ACIEsgEndpointSelectorBulkEditView",
    "ACIEsgEndpointSelectorBulkImportView",
    "ACIEsgEndpointSelectorEditView",
    "ACIEsgEndpointSelectorListView",
    "ACIEsgEndpointSelectorView",
    # ACIExternalEndpointGroup
    "ACIExternalEndpointGroupBulkDeleteView",
    "ACIExternalEndpointGroupBulkEditView",
    "ACIExternalEndpointGroupBulkImportView",
    "ACIExternalEndpointGroupEditView",
    "ACIExternalEndpointGroupListView",
    "ACIExternalEndpointGroupView",
    # ACIExternalSubnet
    "ACIExternalSubnetBulkDeleteView",
    "ACIExternalSubnetBulkEditView",
    "ACIExternalSubnetBulkImportView",
    "ACIExternalSubnetEditView",
    "ACIExternalSubnetListView",
    "ACIExternalSubnetView",
    # ACIFabric
    "ACIFabricBulkDeleteView",
    "ACIFabricBulkEditView",
    "ACIFabricBulkImportView",
    "ACIFabricEditView",
    "ACIFabricListView",
    "ACIFabricView",
    # ACIL3Out
    "ACIL3OutBulkDeleteView",
    "ACIL3OutBulkEditView",
    "ACIL3OutBulkImportView",
    "ACIL3OutEditView",
    "ACIL3OutListView",
    "ACIL3OutView",
    # ACILeafInterfaceOverride
    "ACILeafInterfaceOverrideBulkDeleteView",
    "ACILeafInterfaceOverrideBulkEditView",
    "ACILeafInterfaceOverrideBulkImportView",
    "ACILeafInterfaceOverrideEditView",
    "ACILeafInterfaceOverrideListView",
    "ACILeafInterfaceOverrideView",
    # ACILeafInterfacePolicyGroup
    "ACILeafInterfacePolicyGroupBulkDeleteView",
    "ACILeafInterfacePolicyGroupBulkEditView",
    "ACILeafInterfacePolicyGroupBulkImportView",
    "ACILeafInterfacePolicyGroupEditView",
    "ACILeafInterfacePolicyGroupListView",
    "ACILeafInterfacePolicyGroupView",
    # ACILeafInterfaceProfile
    "ACILeafInterfaceProfileBulkDeleteView",
    "ACILeafInterfaceProfileBulkEditView",
    "ACILeafInterfaceProfileBulkImportView",
    "ACILeafInterfaceProfileEditView",
    "ACILeafInterfaceProfileListView",
    "ACILeafInterfaceProfileView",
    # ACILeafInterfaceSelector
    "ACILeafInterfaceSelectorBulkDeleteView",
    "ACILeafInterfaceSelectorBulkEditView",
    "ACILeafInterfaceSelectorBulkImportView",
    "ACILeafInterfaceSelectorEditView",
    "ACILeafInterfaceSelectorListView",
    "ACILeafInterfaceSelectorView",
    # ACILeafNodeBlock
    "ACILeafNodeBlockBulkDeleteView",
    "ACILeafNodeBlockBulkEditView",
    "ACILeafNodeBlockBulkImportView",
    "ACILeafNodeBlockEditView",
    "ACILeafNodeBlockListView",
    "ACILeafNodeBlockView",
    # ACILeafPortBlock
    "ACILeafPortBlockBulkDeleteView",
    "ACILeafPortBlockBulkEditView",
    "ACILeafPortBlockBulkImportView",
    "ACILeafPortBlockEditView",
    "ACILeafPortBlockListView",
    "ACILeafPortBlockView",
    # ACILeafSelector
    "ACILeafSelectorBulkDeleteView",
    "ACILeafSelectorBulkEditView",
    "ACILeafSelectorBulkImportView",
    "ACILeafSelectorEditView",
    "ACILeafSelectorListView",
    "ACILeafSelectorView",
    # ACILeafSwitchProfile
    "ACILeafSwitchProfileBulkDeleteView",
    "ACILeafSwitchProfileBulkEditView",
    "ACILeafSwitchProfileBulkImportView",
    "ACILeafSwitchProfileEditView",
    "ACILeafSwitchProfileListView",
    "ACILeafSwitchProfileView",
    # ACILeafSwitchProfileInterfaceBinding
    "ACILeafSwitchProfileInterfaceBindingBulkDeleteView",
    "ACILeafSwitchProfileInterfaceBindingBulkEditView",
    "ACILeafSwitchProfileInterfaceBindingBulkImportView",
    "ACILeafSwitchProfileInterfaceBindingEditView",
    "ACILeafSwitchProfileInterfaceBindingListView",
    "ACILeafSwitchProfileInterfaceBindingView",
    # ACINode
    "ACINodeBulkDeleteView",
    "ACINodeBulkEditView",
    "ACINodeBulkImportView",
    "ACINodeEditView",
    "ACINodeListView",
    "ACINodeView",
    # ACINodeInterface
    "ACINodeInterfaceBulkDeleteView",
    "ACINodeInterfaceBulkEditView",
    "ACINodeInterfaceBulkImportView",
    "ACINodeInterfaceEditView",
    "ACINodeInterfaceListView",
    "ACINodeInterfaceView",
    # ACIPhysicalDomain
    "ACIPhysicalDomainBulkDeleteView",
    "ACIPhysicalDomainBulkEditView",
    "ACIPhysicalDomainBulkImportView",
    "ACIPhysicalDomainEditView",
    "ACIPhysicalDomainListView",
    "ACIPhysicalDomainView",
    # ACIPod
    "ACIPodBulkDeleteView",
    "ACIPodBulkEditView",
    "ACIPodBulkImportView",
    "ACIPodEditView",
    "ACIPodListView",
    "ACIPodView",
    # ACIRoutedDomain
    "ACIRoutedDomainBulkDeleteView",
    "ACIRoutedDomainBulkEditView",
    "ACIRoutedDomainBulkImportView",
    "ACIRoutedDomainEditView",
    "ACIRoutedDomainListView",
    "ACIRoutedDomainView",
    # ACITenant
    "ACITenantBulkDeleteView",
    "ACITenantBulkEditView",
    "ACITenantBulkImportView",
    "ACITenantEditView",
    "ACITenantListView",
    "ACITenantView",
    # ACIUSegEndpointGroup
    "ACIUSegEndpointGroupBulkDeleteView",
    "ACIUSegEndpointGroupBulkEditView",
    "ACIUSegEndpointGroupBulkImportView",
    "ACIUSegEndpointGroupEditView",
    "ACIUSegEndpointGroupListView",
    "ACIUSegEndpointGroupView",
    # ACIUSegNetworkAttribute
    "ACIUSegNetworkAttributeBulkDeleteView",
    "ACIUSegNetworkAttributeBulkEditView",
    "ACIUSegNetworkAttributeBulkImportView",
    "ACIUSegNetworkAttributeEditView",
    "ACIUSegNetworkAttributeListView",
    "ACIUSegNetworkAttributeView",
    # ACIVLANPool
    "ACIVLANPoolBulkDeleteView",
    "ACIVLANPoolBulkEditView",
    "ACIVLANPoolBulkImportView",
    "ACIVLANPoolEditView",
    "ACIVLANPoolListView",
    "ACIVLANPoolView",
    # ACIVLANPoolRange
    "ACIVLANPoolRangeBulkDeleteView",
    "ACIVLANPoolRangeBulkEditView",
    "ACIVLANPoolRangeBulkImportView",
    "ACIVLANPoolRangeEditView",
    "ACIVLANPoolRangeListView",
    "ACIVLANPoolRangeView",
    # ACIVPCProtectionGroup
    "ACIVPCProtectionGroupBulkDeleteView",
    "ACIVPCProtectionGroupBulkEditView",
    "ACIVPCProtectionGroupBulkImportView",
    "ACIVPCProtectionGroupEditView",
    "ACIVPCProtectionGroupListView",
    "ACIVPCProtectionGroupView",
    # ACIVRF
    "ACIVRFBulkDeleteView",
    "ACIVRFBulkEditView",
    "ACIVRFBulkImportView",
    "ACIVRFEditView",
    "ACIVRFListView",
    "ACIVRFView",
)
