import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0122_charfield_null_choices"),
        ("ipam", "0076_natural_ordering"),
        ("netbox_aci_plugin", "0005_tenant_contracts"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aciappprofile",
            name="unique_aci_app_profile_name_per_aci_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="acibridgedomain",
            name="unique_aci_bridge_domain_name_per_aci_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="acibridgedomainsubnet",
            name="unique_aci_bd_subnet_name_per_aci_bridge_domain",
        ),
        migrations.RemoveConstraint(
            model_name="acibridgedomainsubnet",
            name="unique_aci_bd_subnet_gateway_ip_per_aci_bridge_domain",
        ),
        migrations.RemoveConstraint(
            model_name="acicontract",
            name="unique_aci_contract_name_per_aci_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="acicontractfilter",
            name="unique_aci_contract_filter_name_per_aci_tenant",
        ),
        migrations.RemoveConstraint(
            model_name="acicontractfilterentry",
            name="unique_aci_filter_entry_name_per_aci_contract_filter",
        ),
        migrations.RemoveConstraint(
            model_name="acicontractrelation",
            name="unique_aci_object_relation_role_per_aci_contract",
        ),
        migrations.RemoveConstraint(
            model_name="acicontractsubject",
            name="unique_aci_contract_subject_name_per_aci_contract",
        ),
        migrations.RemoveConstraint(
            model_name="acicontractsubjectfilter",
            name="unique_aci_contract_filter_per_aci_contract_subject",
        ),
        migrations.RemoveConstraint(
            model_name="aciendpointgroup",
            name="unique_endpoint_group_name_per_aci_app_profile",
        ),
        migrations.RemoveConstraint(
            model_name="acitenant",
            name="unique_aci_tenant_name",
        ),
        migrations.RemoveConstraint(
            model_name="acivrf",
            name="unique_aci_vrf_name_per_aci_tenant",
        ),
        migrations.AddField(
            model_name="acicontractfilterentry",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="aciappprofile",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomainsubnet",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="acicontract",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="acicontractfilter",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="acicontractrelation",
            name="aci_object_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="acicontractsubject",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointgroup",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="acitenant",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="acivrf",
            name="nb_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss",
                to="tenancy.tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="aciappprofile",
            constraint=models.UniqueConstraint(
                fields=("aci_tenant", "name"),
                name="netbox_aci_plugin_aciappprofile_unique_per_aci_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="acibridgedomain",
            constraint=models.UniqueConstraint(
                fields=("aci_tenant", "name"),
                name="netbox_aci_plugin_acibridgedomain_unique_per_aci_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="acibridgedomainsubnet",
            constraint=models.UniqueConstraint(
                fields=("aci_bridge_domain", "name"),
                name="netbox_aci_plugin_acibridgedomainsubnet_unique_per_aci_bridge_domain",
            ),
        ),
        migrations.AddConstraint(
            model_name="acibridgedomainsubnet",
            constraint=models.UniqueConstraint(
                fields=("aci_bridge_domain", "gateway_ip_address"),
                name="netbox_aci_plugin_acibridgedomainsubnet_unique_per_gateway_ip_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="acicontract",
            constraint=models.UniqueConstraint(
                fields=("aci_tenant", "name"),
                name="netbox_aci_plugin_acicontract_unique_per_aci_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="acicontractfilter",
            constraint=models.UniqueConstraint(
                fields=("aci_tenant", "name"),
                name="netbox_aci_plugin_acicontractfilter_unique_per_aci_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="acicontractfilterentry",
            constraint=models.UniqueConstraint(
                fields=("aci_contract_filter", "name"),
                name="netbox_aci_plugin_acicontractfilterentry_unique_per_aci_contract_filter",
            ),
        ),
        migrations.AddConstraint(
            model_name="acicontractrelation",
            constraint=models.UniqueConstraint(
                fields=(
                    "aci_contract",
                    "aci_object_type",
                    "aci_object_id",
                    "role",
                ),
                name="netbox_aci_plugin_acicontractrelation_unique_per_aci_contract_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="acicontractsubject",
            constraint=models.UniqueConstraint(
                fields=("aci_contract", "name"),
                name="netbox_aci_plugin_acicontractsubject_unique_per_aci_contract",
            ),
        ),
        migrations.AddConstraint(
            model_name="acicontractsubjectfilter",
            constraint=models.UniqueConstraint(
                fields=("aci_contract_subject", "aci_contract_filter"),
                name="netbox_aci_plugin_acicontractsubjectfilter_unique_per_aci_contract_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="aciendpointgroup",
            constraint=models.UniqueConstraint(
                fields=("aci_app_profile", "name"),
                name="netbox_aci_plugin_aciendpointgroup_unique_per_aci_app_profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="acitenant",
            constraint=models.UniqueConstraint(
                fields=("name",),
                name="netbox_aci_plugin_acitenant_unique_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="acivrf",
            constraint=models.UniqueConstraint(
                fields=("aci_tenant", "name"),
                name="netbox_aci_plugin_acivrf_unique_per_aci_tenant",
            ),
        ),
    ]
