import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_aci_plugin", "0009_alter_aciendpointgroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aciappprofile",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciappprofile",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciappprofile",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="dhcp_labels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=64,
                    validators=[
                        django.core.validators.RegexValidator(
                            code="invalid",
                            message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                            regex="^[A-Za-z0-9_.:-]*$",
                        )
                    ],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="igmp_interface_policy_name",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="igmp_snooping_policy_name",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="pim_ipv4_destination_filter",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="pim_ipv4_source_filter",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomainsubnet",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomainsubnet",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomainsubnet",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomainsubnet",
            name="nd_ra_prefix_policy_name",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontract",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontract",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontract",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractfilter",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractfilter",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractfilter",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractfilterentry",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractfilterentry",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractfilterentry",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractsubject",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractsubject",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractsubject",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractsubject",
            name="service_graph_name",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractsubject",
            name="service_graph_name_cons_to_prov",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acicontractsubject",
            name="service_graph_name_prov_to_cons",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointgroup",
            name="custom_qos_policy_name",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointgroup",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointgroup",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointgroup",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointsecuritygroup",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointsecuritygroup",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointsecuritygroup",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciesgendpointgroupselector",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciesgendpointgroupselector",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciesgendpointgroupselector",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciesgendpointselector",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciesgendpointselector",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciesgendpointselector",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acitenant",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acitenant",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acitenant",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciusegendpointgroup",
            name="custom_qos_policy_name",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciusegendpointgroup",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciusegendpointgroup",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciusegendpointgroup",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciusegnetworkattribute",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciusegnetworkattribute",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="aciusegnetworkattribute",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acivrf",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters and !#$%%()*,-./:;@ _{|}~?&+ are allowed.",
                        regex="^[A-Za-z0-9!#$%()*,-./:;@ _{|}~?&+]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acivrf",
            name="dns_labels",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=64,
                    validators=[
                        django.core.validators.RegexValidator(
                            code="invalid",
                            message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                            regex="^[A-Za-z0-9_.:-]*$",
                        )
                    ],
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="acivrf",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="acivrf",
            name="name_alias",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid",
                        message="Only alphanumeric characters, periods, underscores, colons and hyphens are allowed.",
                        regex="^[A-Za-z0-9_.:-]*$",
                    )
                ],
            ),
        ),
    ]
