import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_aci_plugin", "0032_access_policy_leaf_interface_overrides"),
        ("users", "0016_default_ordering_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aciappprofile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciattachableaccessentityprofile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomain",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acibridgedomainsubnet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acicontract",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acicontractfilter",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acicontractfilterentry",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acicontractsubject",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointgroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciendpointsecuritygroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciesgendpointgroupselector",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciesgendpointselector",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciexternalendpointgroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciexternalsubnet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acifabric",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acil3out",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acinode",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciphysicaldomain",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acipod",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acirouteddomain",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acitenant",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciusegendpointgroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="aciusegnetworkattribute",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acivlanpool",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
        migrations.AlterField(
            model_name="acivrf",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="users.owner",
            ),
        ),
    ]
