# SPDX-FileCopyrightText: 2024 Martin Hauser
#
# SPDX-License-Identifier: GPL-3.0-or-later

from django.urls import include, path
from utilities.urls import get_model_urls

from .views.tenant_app_profiles import (
    ACIAppProfileBulkDeleteView,
    ACIAppProfileBulkEditView,
    ACIAppProfileBulkImportView,
    ACIAppProfileEditView,
    ACIAppProfileListView,
    ACIEndpointGroupBulkDeleteView,
    ACIEndpointGroupBulkEditView,
    ACIEndpointGroupBulkImportView,
    ACIEndpointGroupEditView,
    ACIEndpointGroupListView,
)
from .views.tenant_contract_filters import (
    ACIContractFilterBulkDeleteView,
    ACIContractFilterBulkEditView,
    ACIContractFilterBulkImportView,
    ACIContractFilterEditView,
    ACIContractFilterEntryBulkDeleteView,
    ACIContractFilterEntryBulkEditView,
    ACIContractFilterEntryBulkImportView,
    ACIContractFilterEntryEditView,
    ACIContractFilterEntryListView,
    ACIContractFilterListView,
)
from .views.tenant_contracts import (
    ACIContractBulkDeleteView,
    ACIContractBulkEditView,
    ACIContractBulkImportView,
    ACIContractEditView,
    ACIContractListView,
    ACIContractRelationBulkDeleteView,
    ACIContractRelationBulkEditView,
    ACIContractRelationBulkImportView,
    ACIContractRelationEditView,
    ACIContractRelationListView,
    ACIContractSubjectBulkDeleteView,
    ACIContractSubjectBulkEditView,
    ACIContractSubjectBulkImportView,
    ACIContractSubjectEditView,
    ACIContractSubjectFilterBulkDeleteView,
    ACIContractSubjectFilterBulkEditView,
    ACIContractSubjectFilterBulkImportView,
    ACIContractSubjectFilterEditView,
    ACIContractSubjectFilterListView,
    ACIContractSubjectListView,
)
from .views.tenant_networks import (
    ACIBridgeDomainBulkDeleteView,
    ACIBridgeDomainBulkEditView,
    ACIBridgeDomainBulkImportView,
    ACIBridgeDomainEditView,
    ACIBridgeDomainListView,
    ACIBridgeDomainSubnetBulkDeleteView,
    ACIBridgeDomainSubnetBulkEditView,
    ACIBridgeDomainSubnetBulkImportView,
    ACIBridgeDomainSubnetEditView,
    ACIBridgeDomainSubnetListView,
    ACIVRFBulkDeleteView,
    ACIVRFBulkEditView,
    ACIVRFBulkImportView,
    ACIVRFEditView,
    ACIVRFListView,
)
from .views.tenants import (
    ACITenantBulkDeleteView,
    ACITenantBulkEditView,
    ACITenantBulkImportView,
    ACITenantEditView,
    ACITenantListView,
)

urlpatterns: tuple = (
    # ACI Tenants
    path("tenants/", ACITenantListView.as_view(), name="acitenant_list"),
    path("tenants/add/", ACITenantEditView.as_view(), name="acitenant_add"),
    path(
        "tenants/delete/",
        ACITenantBulkDeleteView.as_view(),
        name="acitenant_bulk_delete",
    ),
    path(
        "tenants/edit/",
        ACITenantBulkEditView.as_view(),
        name="acitenant_bulk_edit",
    ),
    path(
        "tenants/import/",
        ACITenantBulkImportView.as_view(),
        name="acitenant_import",
    ),
    path(
        "tenants/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "acitenant")),
    ),
    # ACI Application Profiles
    path(
        "app-profiles/",
        ACIAppProfileListView.as_view(),
        name="aciappprofile_list",
    ),
    path(
        "app-profiles/add/",
        ACIAppProfileEditView.as_view(),
        name="aciappprofile_add",
    ),
    path(
        "app-profiles/delete/",
        ACIAppProfileBulkDeleteView.as_view(),
        name="aciappprofile_bulk_delete",
    ),
    path(
        "app-profiles/edit/",
        ACIAppProfileBulkEditView.as_view(),
        name="aciappprofile_bulk_edit",
    ),
    path(
        "app-profiles/import/",
        ACIAppProfileBulkImportView.as_view(),
        name="aciappprofile_import",
    ),
    path(
        "app-profiles/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "aciappprofile")),
    ),
    # ACI Endpoint Group
    path(
        "endpoint-groups/",
        ACIEndpointGroupListView.as_view(),
        name="aciendpointgroup_list",
    ),
    path(
        "endpoint-groups/add/",
        ACIEndpointGroupEditView.as_view(),
        name="aciendpointgroup_add",
    ),
    path(
        "endpoint-groups/delete/",
        ACIEndpointGroupBulkDeleteView.as_view(),
        name="aciendpointgroup_bulk_delete",
    ),
    path(
        "endpoint-groups/edit/",
        ACIEndpointGroupBulkEditView.as_view(),
        name="aciendpointgroup_bulk_edit",
    ),
    path(
        "endpoint-groups/import/",
        ACIEndpointGroupBulkImportView.as_view(),
        name="aciendpointgroup_import",
    ),
    path(
        "endpoint-groups/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "aciendpointgroup")),
    ),
    # ACI Bridge Domain
    path(
        "bridge-domains/",
        ACIBridgeDomainListView.as_view(),
        name="acibridgedomain_list",
    ),
    path(
        "bridge-domains/add/",
        ACIBridgeDomainEditView.as_view(),
        name="acibridgedomain_add",
    ),
    path(
        "bridge-domains/delete/",
        ACIBridgeDomainBulkDeleteView.as_view(),
        name="acibridgedomain_bulk_delete",
    ),
    path(
        "bridge-domains/edit/",
        ACIBridgeDomainBulkEditView.as_view(),
        name="acibridgedomain_bulk_edit",
    ),
    path(
        "bridge-domains/import/",
        ACIBridgeDomainBulkImportView.as_view(),
        name="acibridgedomain_import",
    ),
    path(
        "bridge-domains/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "acibridgedomain")),
    ),
    # ACI Bridge Domain Subnet
    path(
        "bridge-domain-subnets/",
        ACIBridgeDomainSubnetListView.as_view(),
        name="acibridgedomainsubnet_list",
    ),
    path(
        "bridge-domain-subnets/add/",
        ACIBridgeDomainSubnetEditView.as_view(),
        name="acibridgedomainsubnet_add",
    ),
    path(
        "bridge-domain-subnets/delete/",
        ACIBridgeDomainSubnetBulkDeleteView.as_view(),
        name="acibridgedomainsubnet_bulk_delete",
    ),
    path(
        "bridge-domain-subnets/edit/",
        ACIBridgeDomainSubnetBulkEditView.as_view(),
        name="acibridgedomainsubnet_bulk_edit",
    ),
    path(
        "bridge-domain-subnets/import/",
        ACIBridgeDomainSubnetBulkImportView.as_view(),
        name="acibridgedomainsubnet_import",
    ),
    path(
        "bridge-domain-subnets/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "acibridgedomainsubnet")),
    ),
    # ACI VRF
    path("vrfs/", ACIVRFListView.as_view(), name="acivrf_list"),
    path("vrfs/add/", ACIVRFEditView.as_view(), name="acivrf_add"),
    path(
        "vrfs/delete/",
        ACIVRFBulkDeleteView.as_view(),
        name="acivrf_bulk_delete",
    ),
    path(
        "vrfs/edit/",
        ACIVRFBulkEditView.as_view(),
        name="acivrf_bulk_edit",
    ),
    path(
        "vrfs/import/",
        ACIVRFBulkImportView.as_view(),
        name="acivrf_import",
    ),
    path(
        "vrfs/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "acivrf")),
    ),
    # ACI Contract Filter
    path(
        "contract-filters/",
        ACIContractFilterListView.as_view(),
        name="acicontractfilter_list",
    ),
    path(
        "contract-filters/add/",
        ACIContractFilterEditView.as_view(),
        name="acicontractfilter_add",
    ),
    path(
        "contract-filters/delete/",
        ACIContractFilterBulkDeleteView.as_view(),
        name="acicontractfilter_bulk_delete",
    ),
    path(
        "contract-filters/edit/",
        ACIContractFilterBulkEditView.as_view(),
        name="acicontractfilter_bulk_edit",
    ),
    path(
        "contract-filters/import/",
        ACIContractFilterBulkImportView.as_view(),
        name="acicontractfilter_import",
    ),
    path(
        "contract-filters/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "acicontractfilter")),
    ),
    # ACI Contract Filter Entry
    path(
        "contract-filter-entries/",
        ACIContractFilterEntryListView.as_view(),
        name="acicontractfilterentry_list",
    ),
    path(
        "contract-filter-entries/add/",
        ACIContractFilterEntryEditView.as_view(),
        name="acicontractfilterentry_add",
    ),
    path(
        "contract-filter-entries/delete/",
        ACIContractFilterEntryBulkDeleteView.as_view(),
        name="acicontractfilterentry_bulk_delete",
    ),
    path(
        "contract-filter-entries/edit/",
        ACIContractFilterEntryBulkEditView.as_view(),
        name="acicontractfilterentry_bulk_edit",
    ),
    path(
        "contract-filter-entries/import/",
        ACIContractFilterEntryBulkImportView.as_view(),
        name="acicontractfilterentry_import",
    ),
    path(
        "contract-filter-entries/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "acicontractfilterentry")),
    ),
    # ACI Contract
    path(
        "contracts/",
        ACIContractListView.as_view(),
        name="acicontract_list",
    ),
    path(
        "contracts/add/",
        ACIContractEditView.as_view(),
        name="acicontract_add",
    ),
    path(
        "contracts/delete/",
        ACIContractBulkDeleteView.as_view(),
        name="acicontract_bulk_delete",
    ),
    path(
        "contracts/edit/",
        ACIContractBulkEditView.as_view(),
        name="acicontract_bulk_edit",
    ),
    path(
        "contracts/import/",
        ACIContractBulkImportView.as_view(),
        name="acicontract_import",
    ),
    path(
        "contracts/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "acicontract")),
    ),
    # ACI Contract Relation
    path(
        "contracts/relations/",
        ACIContractRelationListView.as_view(),
        name="acicontractrelation_list",
    ),
    path(
        "contracts/relations/add/",
        ACIContractRelationEditView.as_view(),
        name="acicontractrelation_add",
    ),
    path(
        "contracts/relations/delete/",
        ACIContractRelationBulkDeleteView.as_view(),
        name="acicontractrelation_bulk_delete",
    ),
    path(
        "contracts/relations/edit/",
        ACIContractRelationBulkEditView.as_view(),
        name="acicontractrelation_bulk_edit",
    ),
    path(
        "contracts/relations/import/",
        ACIContractRelationBulkImportView.as_view(),
        name="acicontractrelation_import",
    ),
    path(
        "contracts/relations/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "acicontractrelation")),
    ),
    # ACI Contract Subject
    path(
        "contract-subjects/",
        ACIContractSubjectListView.as_view(),
        name="acicontractsubject_list",
    ),
    path(
        "contract-subjects/add/",
        ACIContractSubjectEditView.as_view(),
        name="acicontractsubject_add",
    ),
    path(
        "contract-subjects/delete/",
        ACIContractSubjectBulkDeleteView.as_view(),
        name="acicontractsubject_bulk_delete",
    ),
    path(
        "contract-subjects/edit/",
        ACIContractSubjectBulkEditView.as_view(),
        name="acicontractsubject_bulk_edit",
    ),
    path(
        "contract-subjects/import/",
        ACIContractSubjectBulkImportView.as_view(),
        name="acicontractsubject_import",
    ),
    path(
        "contract-subjects/<int:pk>/",
        include(get_model_urls("netbox_aci_plugin", "acicontractsubject")),
    ),
    # ACI Contract Subject Filter
    path(
        "contract-subjects/filters/",
        ACIContractSubjectFilterListView.as_view(),
        name="acicontractsubjectfilter_list",
    ),
    path(
        "contract-subjects/filters/add/",
        ACIContractSubjectFilterEditView.as_view(),
        name="acicontractsubjectfilter_add",
    ),
    path(
        "contract-subjects/filters/delete/",
        ACIContractSubjectFilterBulkDeleteView.as_view(),
        name="acicontractsubjectfilter_bulk_delete",
    ),
    path(
        "contract-subjects/filters/edit/",
        ACIContractSubjectFilterBulkEditView.as_view(),
        name="acicontractsubjectfilter_bulk_edit",
    ),
    path(
        "contract-subjects/filters/import/",
        ACIContractSubjectFilterBulkImportView.as_view(),
        name="acicontractsubjectfilter_import",
    ),
    path(
        "contract-subjects/filters/<int:pk>/",
        include(
            get_model_urls("netbox_aci_plugin", "acicontractsubjectfilter")
        ),
    ),
)
